"""Typed gridstatus.io series fetch — the structured counterpart to markets.py.

get_market_data (markets.py) hands the LLM a formatted text summary of
whatever columns a dataset returns — fine for free-form questions, but
callers that need real numbers to do arithmetic with (e.g.
compare_forecast_to_actual, which aligns a price forecast against what
actually settled) need parsed points, not a string to re-parse.

Shares the HTTP call + quota/rate-limit fallback behavior with
markets.py's get_market_data (see `_fetch_payload`); each module builds
its own output shape (text vs. typed points) from that shared core.
"""

import hashlib
import math
import os
import random
from datetime import UTC, datetime, timedelta
from typing import Any, Final

import httpx
from pydantic import BaseModel

from ..isotime import iso_z

GRIDSTATUS_BASE_URL: Final[str] = "https://api.gridstatus.io/v1"
HTTP_TIMEOUT_SEC: Final[float] = 15.0
# Status codes that mean "upstream is refusing us" rather than "you sent
# a bad request" — synthesise for these so callers keep working.
_SYNTHETIC_TRIGGER_STATUS: Final[frozenset[int]] = frozenset({403, 404, 429})
# Log-normal baseline for synthetic price points — plausible magnitudes
# only, not fit to any real distribution. Mirrors markets.py's own
# fallback constants so both paths "look" the same when faked.
_SYNTHETIC_LOG_MEAN: Final[float] = 3.5
_SYNTHETIC_LOG_STD: Final[float] = 0.4
_SYNTHETIC_SPIKE_PROB: Final[float] = 0.05
_SYNTHETIC_SPIKE_MIN: Final[float] = 10.0
_SYNTHETIC_SPIKE_MAX: Final[float] = 40.0


class _InvalidApiKeyError(Exception):
    """gridstatus rejected GRIDSTATUS_API_KEY (401) — a real config problem."""


class _GridstatusUnavailableError(Exception):
    """gridstatus signalled quota/rate-limit/unknown-dataset — fall back."""

    def __init__(self, status: int) -> None:
        self.status = status
        super().__init__(f"gridstatus unavailable: HTTP {status}")


class MarketPricePoint(BaseModel):
    """One priced hour from a gridstatus.io dataset query.

    `is_synthetic` flags rows generated by the quota/rate-limit fallback
    instead of a real gridstatus response — callers comparing this
    against a forecast need to know which is which before calling it
    "actual."
    """

    ts: datetime
    value: float
    is_synthetic: bool = False


async def _fetch_payload(
    dataset: str,
    start: str | None,
    end: str | None,
    limit: int,
    location: str | None,
) -> dict[str, Any]:
    """Shared gridstatus GET — params, auth, status dispatch.

    Raises:
        ValueError: GRIDSTATUS_API_KEY not set.
        _InvalidApiKeyError: gridstatus rejected the key (401).
        _GridstatusUnavailableError: quota/rate-limit/unknown-dataset (403/404/429).
        httpx.HTTPStatusError: any other HTTP error (e.g. 500).
        httpx.RequestError: network failure.
    """
    api_key = os.environ.get("GRIDSTATUS_API_KEY", "")
    if not api_key:
        raise ValueError(
            "GRIDSTATUS_API_KEY environment variable not set. "
            "Get a key from https://www.gridstatus.io"
        )
    params: dict[str, Any] = {"limit": limit}
    if start is not None:
        params["start_time"] = start
    if end is not None:
        params["end_time"] = end
    if location is not None:
        # Reason: gridstatus's generic row filter, not a dedicated location
        # param — verified directly against the live API.
        params["filter_column"] = "location"
        params["filter_value"] = location
        params["filter_operator"] = "="

    async with httpx.AsyncClient() as client:
        resp = await client.get(
            f"{GRIDSTATUS_BASE_URL}/datasets/{dataset}/query",
            params=params,
            headers={"x-api-key": api_key},
            timeout=HTTP_TIMEOUT_SEC,
        )
        try:
            resp.raise_for_status()
        except httpx.HTTPStatusError as e:
            if e.response.status_code == 401:
                raise _InvalidApiKeyError from e
            if e.response.status_code in _SYNTHETIC_TRIGGER_STATUS:
                raise _GridstatusUnavailableError(e.response.status_code) from e
            raise
        return resp.json()


def _synthetic_points(anchor: datetime, n_rows: int, seed_key: str) -> list[MarketPricePoint]:
    """Deterministic plausible price points, hourly, ending at `anchor`.

    Seeded by seed_key — same inputs produce the same numbers so a
    retry within one turn doesn't flap.
    """
    seed = int(hashlib.sha256(seed_key.encode()).hexdigest()[:16], 16)
    # Reason: non-crypto — this seeds fake price points, not secrets.
    rng = random.Random(seed)  # noqa: S311  # nosec B311
    points: list[MarketPricePoint] = []
    for i in range(n_rows):
        ts = anchor - timedelta(hours=n_rows - i - 1)
        base = math.exp(rng.gauss(_SYNTHETIC_LOG_MEAN, _SYNTHETIC_LOG_STD))
        if rng.random() < _SYNTHETIC_SPIKE_PROB:
            base *= rng.uniform(_SYNTHETIC_SPIKE_MIN, _SYNTHETIC_SPIKE_MAX)
        points.append(MarketPricePoint(ts=ts, value=round(base, 2), is_synthetic=True))
    return points


async def fetch_market_series(
    dataset: str,
    location: str,
    ts_column: str,
    value_column: str,
    start: datetime,
    end: datetime,
    limit: int,
) -> list[MarketPricePoint]:
    """Typed gridstatus.io series fetch — parsed points, not LLM text.

    On 403/404/429 (no paid gridstatus tier right now) falls back to a
    deterministic synthetic hourly series spanning the same window,
    flagged via `is_synthetic` — callers must surface that flag rather
    than present it as real settlement data.

    Args:
        dataset: gridstatus dataset slug, e.g. 'ercot_spp_day_ahead_hourly'.
        location: Exact `location` column value to filter to, e.g. 'HB_NORTH'.
        ts_column: Name of the timestamp column in the dataset's rows.
        value_column: Name of the price column in the dataset's rows.
        start: Window start (inclusive).
        end: Window end (inclusive).
        limit: Row cap — callers should size this to the window (e.g.
            hours-in-window + a small buffer), not the LLM-text default.

    Returns:
        Points sorted as returned by gridstatus (real), or one synthetic
        point per hour across [start, end] (fallback).

    Raises:
        ValueError: GRIDSTATUS_API_KEY not set.
        _InvalidApiKeyError: gridstatus rejected the key (401).
        httpx.HTTPStatusError: any other HTTP error (e.g. 500).
        httpx.RequestError: network failure.
    """
    try:
        payload = await _fetch_payload(dataset, iso_z(start), iso_z(end), limit, location)
    except _GridstatusUnavailableError:
        hours = max(int((end - start).total_seconds() // 3600) + 1, 1)
        anchor = end.replace(minute=0, second=0, microsecond=0, tzinfo=UTC)
        seed_key = f"{dataset}|{iso_z(start)}|{iso_z(end)}|{location}"
        return _synthetic_points(anchor, hours, seed_key)
    rows = payload.get("data", [])
    return [
        MarketPricePoint(ts=datetime.fromisoformat(row[ts_column]), value=float(row[value_column]))
        for row in rows
    ]
