"""Demo-mode bootstrap — seed public.measurements from bundled CSV.

When ENV=demo, the analyst-server calls seed_measurements() at startup
so the LLM has real (if synthetic) site data to query — agent reads it
through server's /sites/{id}/measurements endpoint, same path the HMI
uses. Idempotent: skips if the table already has rows.

CSV columns: ts, site_id, device_id, measurement, unit, value
- ts: ISO 8601 UTC ('Z' suffix). Generated by scripts/regen_demo_csv.py
  from a 30-day historical DAM SPP slice.
- value: raw JSON literal (numbers unquoted, strings as "x").

Time shift: at load time we compute `delta = now - max(csv.ts)` and add
delta to every ts. That way "today" in chat always lines up with the
most recent CSV hour — no periodic CSV regen needed just to keep dates
feeling current.

CSV is bundled in the wheel via package-data in pyproject.toml.
"""

import asyncio
import csv
import io
import logging
from datetime import UTC, datetime
from importlib import resources

import asyncpg

log = logging.getLogger(__name__)

_PKG_DATA: str = "ems_analyst_agent.demo_data"
_CSV_NAME: str = "measurements.csv"


def _shift_csv_to_now(csv_bytes: bytes) -> bytes:
    """Read CSV, find max(ts), shift all rows so max(ts) == now (top of hour).

    Returns the shifted CSV bytes ready for `copy_to_table`. Top-of-hour
    snapping keeps shifted ts values aligned on hour boundaries (matches
    the generator's hourly cadence).
    """
    text = csv_bytes.decode("utf-8")
    reader = csv.reader(io.StringIO(text))
    header = next(reader)
    rows = list(reader)
    if not rows:
        return csv_bytes
    ts_col = header.index("ts")
    max_ts = max(datetime.strptime(r[ts_col], "%Y-%m-%dT%H:%M:%SZ") for r in rows)
    target = datetime.now(UTC).replace(minute=0, second=0, microsecond=0, tzinfo=None)
    delta = target - max_ts
    out = io.StringIO()
    writer = csv.writer(out)
    writer.writerow(header)
    for r in rows:
        shifted = (datetime.strptime(r[ts_col], "%Y-%m-%dT%H:%M:%SZ") + delta).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )
        r[ts_col] = shifted
        writer.writerow(r)
    return out.getvalue().encode("utf-8")


async def seed_measurements(postgres_url: str) -> int:
    """Create the measurements table if absent and COPY the demo CSV into it.

    Returns the number of rows after seeding. Returns 0 (skip) if the
    table already has data so a restarted demo container doesn't keep
    stacking. Time-shifts all CSV timestamps so max(ts) == now.
    """
    conn = await asyncpg.connect(postgres_url)
    try:
        # Schema MUST stay byte-for-byte aligned with platform-api's
        # telemetry_writer.py SCHEMA_SQL (every column NOT NULL incl. unit),
        # so the demo seed loads cleanly into a bootstrapped real DB if
        # someone ever runs ENV=demo against a shared backend by mistake.
        await conn.execute("""
            CREATE TABLE IF NOT EXISTS measurements (
                ts          TIMESTAMPTZ NOT NULL,
                site_id     TEXT        NOT NULL,
                device_id   TEXT        NOT NULL,
                measurement TEXT        NOT NULL,
                unit        TEXT        NOT NULL,
                value       JSONB       NOT NULL
            );
            CREATE INDEX IF NOT EXISTS idx_measurements_lookup
                ON measurements (site_id, device_id, measurement, ts DESC);
        """)
        existing = await conn.fetchval("SELECT count(*) FROM public.measurements")
        if existing and existing > 0:
            log.info("demo seed skipped: %d rows already present", existing)
            return int(existing)
        csv_bytes = resources.files(_PKG_DATA).joinpath(_CSV_NAME).read_bytes()
        # Reason: shift in Python (not SQL) keeps the COPY path single +
        # avoids a temp-table dance just to add an INTERVAL. CSV size is
        # ~10k rows — cheap to mutate in memory.
        shifted = await asyncio.to_thread(_shift_csv_to_now, csv_bytes)
        await conn.copy_to_table(
            "measurements",
            source=io.BytesIO(shifted),
            format="csv",
            header=True,
        )
        seeded = await conn.fetchval("SELECT count(*) FROM public.measurements")
        log.info("demo seed loaded %d rows into public.measurements", seeded)
        return int(seeded)
    finally:
        await conn.close()
